services:
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:admin@192.168.200.1:5432/olist_generate?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - cdc-network

networks:
  cdc-network:
    external: true