global:
  scrape_interval: 15s      
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'starrocks_fe'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.200.1:8030'] 

  - job_name: 'starrocks_be'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.200.1:8040'] 

  - job_name: 'flink_cdc'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - '192.168.200.1:9249' 
        - '192.168.200.1:9250'