source:
  type: postgres
  name: Postgres Source
  hostname: 192.168.200.1
  port: 5432
  username: postgres
  password: admin
  tables: 'olist_generate.public.order_items'
  slot.name: flink_slot_order_items
  scan.startup.mode: initial
  
sink:
  type: starrocks
  name: StarRocks Sink
  jdbc-url: jdbc:mysql://192.168.200.1:9030
  load-url: 192.168.200.1:8030
  username: root
  password: ""
  sink.buffer-flush.interval-ms: 5000
  sink.properties.columns: 'order_id, product_id, order_item_id, seller_id, shipping_limit_date, price, freight_value, source_updated_at, starrocks_arrived_at=utc_timestamp()'

pipeline:
  name: Postgres to StarRocks CDC
  parallelism: 1

route:
  - source-table: 'public.\.*'
    sink-table: 'ods.<>'
    replace-symbol: '<>'