source:
  type: postgres
  name: Postgres Source
  hostname: 192.168.200.1
  port: 5432
  username: postgres
  password: admin
  tables: 'olist_generate.public.(?!stg_orders$)[a-zA-Z0-9_]+'
  slot.name: flink_slot
  scan.startup.mode: initial
  
sink:
  type: starrocks
  name: StarRocks Sink
  jdbc-url: jdbc:mysql://192.168.200.1:9030
  load-url: 192.168.200.1:8030
  username: root
  password: ""
  sink.buffer-flush.interval-ms: 5000
  sink.properties.format: json
  sink.properties.columns: 'starrocks_arrived_at=ROUND(UNIX_TIMESTAMP(NOW(3)) * 1000)'  
  sink.properties.timezone: UTC

pipeline:
  name: Postgres to StarRocks CDC
  parallelism: 1
  local-time-zone: "UTC"

route:
  - source-table: 'public.\.*'
    sink-table: 'ods.<>'
    replace-symbol: '<>'